nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

yarnPath: .yarn/releases/yarn-3.2.2.cjs

logFilters:
  # In CI, we should set `GLOBAL_YARN_LOG_LEVEL=error`
  - level: ${GLOBAL_YARN_LOG_LEVEL:-warning}
    pattern: '*'
  # log level `warning` doesn't include log level `error`
  # have to make this config to make sure we don't miss `error` log
  - level: error
    pattern: '*'
